/**
 * GET /feed.xml — the living podcast feed.
 *
 * Generated by scripts/write-feed-endpoint.py; the STATIC list below is the
 * committed run of episodes, refreshed from src/_data/episodes.json whenever
 * the site builds. Everything published through the site's own door is read
 * out of the shelf on request, so a posted episode joins the feed at once —
 * that is the whole reason this file is a page rather than a static file.
 *
 * Enclosure URLs are signed storage URLs with a week to run; feed readers
 * refetch the feed often enough that a fresh signature is always a request
 * away.
 */
import { db, storage } from 'hatchable';

export const access = 'public';
export const methods = ['GET'];

const STATIC = [
  {
    "number": "001",
    "title": "What Is an Egregore? Building a Mind Out of Many Minds",
    "summary": "Edward opens the order: thought-forms, group minds, the sociology of belief, and why naming a thing accurately is the first act of magic.",
    "date": "2026-09-05",
    "audio": ""
  },
  {
    "number": "002",
    "title": "The Grove and the Particle Accelerator",
    "summary": "Why druidry and high-energy physics are asking the same question in different dialects \u2014 pattern, persistence and the behaviour of energy under constraint.",
    "date": "2026-09-19",
    "audio": ""
  },
  {
    "number": "003",
    "title": "Entropic Brains: Psychedelics, Prediction and the Loosening of the Model",
    "summary": "Predictive processing, the default mode network, and what the visionary state actually does to the machinery of perception. With a long caution on set, setting and law.",
    "date": "2026-10-03",
    "audio": ""
  }
];

const esc = (s) => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;')
  .replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const rfc = (d) => {
  const t = new Date(d);
  return isNaN(t.getTime()) ? new Date().toUTCString() : t.toUTCString();
};

export default async function (req, res) {
  const h = (req && req.headers) || {};
  const host = String(h['x-forwarded-host'] || h.host || 'egregora.hatchable.site').split(',')[0].trim();
  const base = 'https://' + host;
  const items = [];

  /* The shelf first — newest published sound, signed and ready. */
  try {
    const { rows } = await db.query(
      `SELECT id, number, title, summary, created_at, storage_key, mime, bytes
         FROM media WHERE kind = 'audio' AND state = 'published'
        ORDER BY created_at DESC LIMIT 100`);
    for (const r of rows || []) {
      let url = null;
      try { url = await storage.url(r.storage_key, { ttl: 604800 }); } catch { url = null; }
      items.push({
        title: (r.number ? r.number + ' — ' : '') + r.title,
        summary: r.summary || '',
        date: r.created_at,
        url, mime: r.mime || 'audio/mpeg', bytes: Number(r.bytes) || 0,
        guid: 'egregora-live-' + r.id
      });
    }
  } catch (err) {
    console.error('feed: the shelf could not be read', err && err.message);
  }

  /* Then the committed run, newest first, so the order of the feed is the
     order of the programme. */
  for (const ep of STATIC.slice().reverse()) {
    items.push({
      title: (ep.number ? ep.number + ' — ' : '') + ep.title,
      summary: ep.summary || '',
      date: ep.date,
      url: ep.audio || null, mime: 'audio/mpeg', bytes: 0,
      guid: 'egregora-ep-' + ep.number
    });
  }

  const out = [];
  out.push('<?xml version="1.0" encoding="utf-8"?>');
  out.push('<rss version="2.0"><channel>');
  out.push('<title>EGregoRA — The Podcast</title>');
  out.push('<link>' + esc(base + '/podcast/') + '</link>');
  out.push('<description>Life, Love, Magic. Long-form conversation from the order — cosmology, druidry, neuroscience and the esoteric, argued at length.</description>');
  out.push('<language>en-gb</language>');
  out.push('<generator>EGregoRA live feed</generator>');
  for (const it of items) {
    out.push('<item>');
    out.push('  <title>' + esc(it.title) + '</title>');
    out.push('  <link>' + esc(base + '/podcast/') + '</link>');
    out.push('  <guid isPermaLink="false">' + esc(it.guid) + '</guid>');
    out.push('  <description>' + esc(it.summary) + '</description>');
    out.push('  <pubDate>' + esc(rfc(it.date)) + '</pubDate>');
    if (it.url) {
      out.push('  <enclosure url="' + esc(it.url) + '" type="' + esc(it.mime) + '"' +
        (it.bytes ? ' length="' + it.bytes + '"' : '') + '/>');
    }
    out.push('</item>');
  }
  out.push('</channel></rss>');

  res.setHeader('content-type', 'application/rss+xml; charset=utf-8');
  res.setHeader('cache-control', 'public, max-age=60');
  return res.send(out.join('\n'));
}
