#!/usr/bin/env python3
"""Rebuild tti/src/plates.njk from every <figure class="plate"> rendered anywhere
on The Two Infinities site. Generated artefact -- do not hand-edit the output."""
import re, pathlib, html

ROOT = pathlib.Path(__file__).resolve().parents[1]
SITE = ROOT / "tti" / "_site"
OUT  = ROOT / "tti" / "src" / "plates.njk"

ORDER = [("","The Opening Page"),("foundations","Foundations"),("the-self","The Self"),("dx","dx"),("skeletal-splice","The Splice"),("megatubule","The Megatubule"),("gravity","Gravity"),
         ("spiral","The Spiral"),("base-ten","Base Ten in Nature"),("torus","Torus"),("moebius","Möbius"),
         ("cosmic-ledger","Cosmic Ledger"),("seams","Seams"),("stress-tests","Stress Tests"),
         ("essays","Essays")]

FIG = re.compile(r'<figure[^>]*class="plate(?: [^"]*)?"[^>]*>.*?</figure>', re.S)
OPEN = re.compile(r'<figure[^>]*>')

def title_of(fig):
    m = re.search(r'<figcaption class="plate-cap">(.*?)</figcaption>', fig, re.S)
    if not m: return "Plate"
    return " ".join(html.unescape(re.sub(r"<[^>]+>", "", m.group(1))).split())

blocks, toc, total = [], [], 0
for slug, label in ORDER:
    f = SITE / slug / "index.html"
    if not f.exists():
        continue
    figs = FIG.findall(f.read_text(encoding="utf-8"))
    if not figs:
        continue
    toc.append((slug, label, len(figs)))
    blocks.append(f'<div class="divider">✦</div>\n')
    blocks.append(
        '<section class="wrap narrow reveal">\n'
        '  <div class="frame">\n'
        f'    <p class="kicker">Gathered from <a href="/{slug}/">{label}</a></p>\n'
        f'    <h2 id="g-{slug}">{label}</h2>\n'
        f'    <p class="muted small">{len(figs)} plate{"s" if len(figs)!=1 else ""}, drawn in place on that page '
        f'and reproduced here unchanged.</p>\n'
        '  </div>\n</section>\n')
    for i, fig in enumerate(figs, 1):
        total += 1
        fig = OPEN.sub(f'<figure class="plate" id="plate-{slug}-{i}">', fig, count=1)
        fig = fig.replace('</figure>',
                          f'  <p class="muted xsmall">Drawn in context on '
                          f'<a href="/{slug}/">{label}</a>.</p>\n</figure>')
        blocks.append(f'<section class="wrap reveal">\n{fig}\n</section>\n')

toc_html = "\n".join(
    f'      <li><a href="#g-{s}">{l}</a> <span class="muted">&mdash; {n} plate{"s" if n!=1 else ""}</span></li>'
    for s, l, n in toc)

head = f'''---
layout: layouts/base.njk
title: The Plates
permalink: /plates/
description: "Every plate drawn anywhere on The Two Infinities, gathered in one place: {total} figures from the log-spiral placement of the integers to the forking tree, the galactic torus, the Mobius parity test, the Ledger's three residues and the infinite choir. All vector, all legible at any size."
---

<!-- GENERATED by scripts/tti-gather-plates.py from tti/_site -- do not hand-edit. -->

<section class="page-head">
  <p class="kicker">The Visual Compendium &middot; {total} plates</p>
  <h1>The Plates</h1>
  <p class="lede muted"><strong>Z</strong>oom as far as you like, nothing will blur.</p>
</section>

<section class="wrap narrow reveal">
  <div class="frame frame--first illuminated">
    <p class="lede">Every figure the site draws, collected. Each one is vector, built in the page it belongs
      to and copied here in full &mdash; same geometry, same numbers, same caption.</p>
    <ul>
{toc_html}
    </ul>
    <p class="muted small">Grading: <span class="sci">&#9670; established</span> &middot;
      <span class="hist">&#9670; scholarship</span> &middot;
      <span class="spec">&#9670; the framework's argument</span> &middot;
      <span class="myth">&#9670; vision, stated as vision</span>.</p>
  </div>
</section>

'''

tail = '''<div class="divider">✦</div>

<section class="wrap narrow reveal">
  <div class="frame frame--creed">
    <p class="lede">A diagram is an argument you can check at a glance. These are kept together so the
      shape of the whole framework can be read before a word of it is.</p>
    <p class="muted small">Next: <a href="/ask-shakdrah/">ask ShakDrah</a>.</p>
  </div>
</section>
'''

OUT.write_text(head + "".join(blocks) + tail, encoding="utf-8")
print(f"wrote {OUT} -- {total} plates across {len(toc)} pages")
