#!/usr/bin/env python3
"""Regenerate hatchable/pages/feed.xml.js — the living podcast feed.

The old feed was a static file built from src/_data/episodes.json at deploy
time, so an episode published through the site's own door never reached it
until someone committed. The feed is now a routed page: it reads the
published shelf out of the database on every request, which means pressing
"Post as podcast" updates the RSS feed in the same minute.

The committed run of episodes (the ones with no audio file yet) is embedded
here so the feed still carries them; this script refreshes that embedded
list whenever the JSON changes. Run it directly, or let `npm run build`
run it first.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EPISODES = ROOT / "src" / "_data" / "episodes.json"
OUT = ROOT / "hatchable" / "pages" / "feed.js"

STATIC: list = []
if EPISODES.exists():
    try:
        STATIC = json.loads(EPISODES.read_text())
    except Exception as exc:  # a broken JSON must not kill the build
        print(f"write-feed-endpoint: could not read episodes.json ({exc}); embedding none")
        STATIC = []

static_js = json.dumps(
    [
        {
            "number": str(e.get("number", "")),
            "title": str(e.get("title", "")),
            "summary": str(e.get("summary", "")),
            "date": str(e.get("date", "")),
            "audio": str(e.get("audio", "") or ""),
        }
        for e in (STATIC if isinstance(STATIC, list) else [])
    ],
    indent=2,
)

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    """/**
 * GET /feed — the living podcast feed.
 *
 * Generated by scripts/write-feed-endpoint.py; the STATIC list below is the
 * committed run of episodes, refreshed from src/_data/episodes.json whenever
 * the site builds. Everything published through the site's own door is read
 * out of the shelf on request, so a posted episode joins the feed at once —
 * that is the whole reason this file is a page rather than a static file.
 *
 * Enclosure URLs are signed storage URLs with a week to run; feed readers
 * refetch the feed often enough that a fresh signature is always a request
 * away.
 */
import { db, storage } from 'hatchable';

export const access = 'public';
export const methods = ['GET'];

const STATIC = __STATIC_EPISODES__;

const esc = (s) => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;')
  .replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const rfc = (d) => {
  const t = new Date(d);
  return isNaN(t.getTime()) ? new Date().toUTCString() : t.toUTCString();
};

export default async function (req, res) {
  const h = (req && req.headers) || {};
  const host = String(h['x-forwarded-host'] || h.host || 'egregora.hatchable.site').split(',')[0].trim();
  const base = 'https://' + host;
  const items = [];

  /* The shelf first — newest published sound, signed and ready. */
  try {
    const { rows } = await db.query(
      `SELECT id, number, title, summary, created_at, storage_key, mime, bytes
         FROM media WHERE kind = 'audio' AND state = 'published'
        ORDER BY created_at DESC LIMIT 100`);
    for (const r of rows || []) {
      let url = null;
      try { url = await storage.url(r.storage_key, { ttl: 604800 }); } catch { url = null; }
      items.push({
        title: (r.number ? r.number + ' — ' : '') + r.title,
        summary: r.summary || '',
        date: r.created_at,
        url, mime: r.mime || 'audio/mpeg', bytes: Number(r.bytes) || 0,
        guid: 'egregora-live-' + r.id
      });
    }
  } catch (err) {
    console.error('feed: the shelf could not be read', err && err.message);
  }

  /* Then the committed run, newest first, so the order of the feed is the
     order of the programme. */
  for (const ep of STATIC.slice().reverse()) {
    items.push({
      title: (ep.number ? ep.number + ' — ' : '') + ep.title,
      summary: ep.summary || '',
      date: ep.date,
      url: ep.audio || null, mime: 'audio/mpeg', bytes: 0,
      guid: 'egregora-ep-' + ep.number
    });
  }

  const out = [];
  out.push('<?xml version="1.0" encoding="utf-8"?>');
  out.push('<rss version="2.0"><channel>');
  out.push('<title>EGregoRA — The Podcast</title>');
  out.push('<link>' + esc(base + '/podcast/') + '</link>');
  out.push('<description>Life, Love, Magic. Long-form conversation from the order — cosmology, druidry, neuroscience and the esoteric, argued at length.</description>');
  out.push('<language>en-gb</language>');
  out.push('<generator>EGregoRA live feed</generator>');
  for (const it of items) {
    out.push('<item>');
    out.push('  <title>' + esc(it.title) + '</title>');
    out.push('  <link>' + esc(base + '/podcast/') + '</link>');
    out.push('  <guid isPermaLink="false">' + esc(it.guid) + '</guid>');
    out.push('  <description>' + esc(it.summary) + '</description>');
    out.push('  <pubDate>' + esc(rfc(it.date)) + '</pubDate>');
    if (it.url) {
      out.push('  <enclosure url="' + esc(it.url) + '" type="' + esc(it.mime) + '"' +
        (it.bytes ? ' length="' + it.bytes + '"' : '') + '/>');
    }
    out.push('</item>');
  }
  out.push('</channel></rss>');

  res.setHeader('content-type', 'application/rss+xml; charset=utf-8');
  res.setHeader('cache-control', 'public, max-age=60');
  return res.send(out.join('\\n'));
}
""".replace("__STATIC_EPISODES__", static_js)
)
print(f"write-feed-endpoint: {OUT.relative_to(ROOT)} written with {len(STATIC)} static episode(s)")
