#!/usr/bin/env python3
"""Write hatchable/lib/site-map.js from src/_data/atlas.json.

The describing model needs to know what the site actually contains before it
can say which sections an episode touches. Rather than keeping a second
hand-written index, this flattens the Atlas — which is itself generated from
the pages — into one list of title => href pairs.

Run after scripts/gather-topics.py.
"""
import json

atlas = json.load(open("src/_data/atlas.json"))
rows = []
for href, sections in sorted(atlas.items()):
    for s in sections:
        rows.append((s["title"], s["href"]))

lines = [
    "/**",
    " * Every section of the site, as a flat list the describing model can link to.",
    " *",
    " * Generated by scripts/write-site-map.py from src/_data/atlas.json \u2014 the same",
    " * list the Atlas draws from, so a new section on a page becomes a place an",
    " * episode can point at without anyone maintaining a second index.",
    " */",
    "export const SECTIONS = [",
]
for t, h in rows:
    lines.append("  { title: %s, href: %s }," % (json.dumps(t), json.dumps(h)))
lines.append("];")
lines.append("")
lines.append("export const SECTION_LINES = SECTIONS.map((s) => s.title + ' => ' + s.href).join('\\n');")
lines.append("")
open("hatchable/lib/site-map.js", "w").write("\n".join(lines))
print("site-map.js:", len(rows), "sections")
