export default {
  name: "EGregoRA",
  tagline: "Life, Love, Magic",
  motto: "An Order of Enquiry into Cosmos, Consciousness & the Living Earth",
  cofounder: "Edward Gregory",
  cofounder2: "Jim Rankin",
  description:
    "EGregoRA — an ornate house of enquiry co-founded by Edward Gregory and Jim Rankin, braiding cosmic physics, natural philosophy, astrology, druidry, sacred geometry, neuroscience, biology and the Law of One into one living study of reality.",
  email: "info@shakra.co.uk",
  url: "https://egregora.hatchable.site",
  locale: "en_GB",
  lang: "en-GB",
  themeColor: "#0d0b10",
  ogImage: "/assets/img/og-egregora.jpg",
  ogImageAlt: "The EGregoRA emblem — an all-seeing eye within Metatron's cube, a tree of stars above it, in gold on black.",
  founded: "2026",
  keywords: "cosmic physics, natural philosophy, sacred geometry, astrology, druidry, consciousness, quantum decoherence, microtubules, the Law of One, Hermetic Qabalah, alchemy, neuroscience, esotericism",
  nav: [
    { url: "/", label: "Introduction", glyph: "seed" },
    { url: "/podcast/", label: "Podcasts", glyph: "spiral" },
    { url: "/videos/", label: "Videos", glyph: "eye" },
    { url: "/ask-ed/", label: "Ask Ed", glyph: "star" },
    { url: "/infographics/", label: "Infographics", glyph: "metatron" },
    { url: "/cosmic-ether/", label: "Cosmic Ether", glyph: "spiral" },
    { url: "/druids/", label: "Druids", glyph: "tree" },
    { url: "/sacred-geometry/", label: "Sacred Geometry", glyph: "seed" },
    { url: "/astrology/", label: "Astrology", glyph: "star" },
    { url: "/artwork/", label: "Artwork", glyph: "eye" },
    { url: "/neurobiology/", label: "Neurobiology", glyph: "star" },
    { url: "/consciousness/", label: "Consciousness", glyph: "metatron" },
    { url: "/decoherence/", label: "Decoherence", glyph: "spiral" },
    { url: "/locality/", label: "Local & Non-Local", glyph: "metatron" },
    { url: "/extraterrestrials/", label: "Extraterrestrials", glyph: "eye" },
    { url: "/music/", label: "Sound & Music", glyph: "spiral" },
    { url: "/wizardry/", label: "Wizardry", glyph: "star" },
    { url: "/runes/", label: "Runes & Charms", glyph: "tree" },
    { url: "/occult/", label: "The Occult", glyph: "eye" },
    { url: "/qabalah/", label: "Hermetic Qabalah", glyph: "tree" },
    { url: "/elemental-alchemy/", label: "Elemental Alchemy", glyph: "spiral" },
    { url: "/products/", label: "Products", glyph: "seed" },
    { url: "/join/", label: "Join", glyph: "star" }
  ]
};
